name: wrf
channels:
  - conda-forge/osx-arm64
  - defaults
dependencies:
  - python
  - ipython
  - xarray
  - pynio
  - netCDF4
  - pyyaml
  - pynio
  - matplotlib
  - cartopy
  - wrf-python
  - geopandas
